export type Catch = {
  id: number;
  user_id: number;
  species: string | null;
  length_cm: number | null;
  weight_kg: number | null;
  lake?: string | null;
  location?: string | null;
  method?: string | null;
  bait?: string | null;
  comment?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  weather_temp_c?: number | null;
  weather_description?: string | null;
  weather_wind_kmh?: number | null;
  weather_wind_dir_deg?: number | null;
  weather_pressure_hpa?: number | null;
  weather_cloud_pct?: number | null;
  caught_at: Date;
  angler_name?: string;
};
