// Utökad katalog med fiskarter som förekommer i svenskt sport- och husbehovsfiske,
// både i sötvatten och längs kusten. Kompletterad med samtliga arter från
// Sportfiskarnas Storfiskregister (även fredade och längdmätta arter utan
// egen viktgräns, se lib/storfisk.ts) så listan täcker det mesta man kan fånga.
export const FISH_SPECIES = [
  "Abborre",
  "Asp",
  "Berggylta",
  "Bergskädda",
  "Björkna",
  "Bleka",
  "Blå Gaffelmakrill",
  "Blågylta",
  "Blåkäft",
  "Blåkäxa",
  "Blålånga",
  "Bonito",
  "Braxen",
  "Brungylta",
  "Brunsnultra",
  "Bäckröding",
  "Faren",
  "Fenknot",
  "Fjällbrosme",
  "Fjärsing",
  "Flundra",
  "Färna",
  "Glyskolja",
  "Gråhaj",
  "Gråsej",
  "Gräskarp",
  "Guldlax",
  "Gädda",
  "Gärs",
  "Gös",
  "Harr",
  "Havsabborre",
  "Havsbraxen",
  "Havskatt",
  "Havsmus",
  "Havsål",
  "Havsöring",
  "Hornsimpa",
  "Håbrand",
  "Hågäl",
  "Håkäring",
  "Hälleflundra",
  "Id",
  "Indianlax",
  "Insjölax",
  "Insjööring",
  "Kanadaröding",
  "Karp",
  "Klorocka",
  "Klumpfisk",
  "Knaggrocka",
  "Knot",
  "Kolja",
  "Kolmule",
  "Kummel",
  "Lake",
  "Lax",
  "Lerskädda",
  "Löja",
  "Lubb",
  "Långa",
  "Makrill",
  "Mal",
  "Marulk",
  "Mindre Kungsfisk",
  "Multe",
  "Mört",
  "Näbbgädda",
  "Nejonöga",
  "Nors",
  "Paddtorsk",
  "Pigghaj",
  "Piggvar",
  "Puckellax",
  "Regnbåge",
  "Ringhaj",
  "Rocka",
  "Ruda",
  "Röding",
  "Rödknot",
  "Rödspätta",
  "Rödtunga",
  "Rötsimpa",
  "Sandskädda",
  "Sarv",
  "Sej",
  "Sik",
  "Sill",
  "Silverruda",
  "Sjurygg",
  "Skoläst",
  "Skrubbskädda",
  "Skäggtorsk",
  "Slätrocka",
  "Slätvar",
  "Småfläckig Rödhaj",
  "Staksill",
  "Strupsnittsöring",
  "Strömming",
  "Stäm",
  "Större Kungsfisk",
  "Sutare",
  "Svart Smörbult",
  "Svartmunnad Smörbult",
  "Taggmakrill",
  "Tjockläppad Multe",
  "Torsk",
  "Tunga",
  "Tunnläppad Multe",
  "Tånglake",
  "Vimma",
  "Vitling",
  "Vitrocka",
  "Vrakfisk",
  "Ål",
  "Öring",
] as const;
